# Generated by Django 4.0.5 on 2022-08-05 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('telephone_number', models.IntegerField(verbose_name='Telephone Number')),
                ('date_brought', models.DateField(verbose_name='Date of Order')),
                ('phone_model', models.CharField(max_length=20, verbose_name='Phone Model')),
                ('description', models.TextField(blank=True, verbose_name='Description of repair')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
