# Generated by Django 4.0.5 on 2022-08-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
