# Generated by Django 4.0.5 on 2022-08-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0002_remove_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telephone_number',
            field=models.CharField(max_length=20, verbose_name='Telephone Number'),
        ),
    ]
