# Generated by Django 4.0.5 on 2022-08-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0004_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spareparts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone Number')),
                ('phone_model', models.CharField(max_length=20, verbose_name='Phone Model')),
                ('spare', models.CharField(max_length=50, verbose_name='Spare Part')),
            ],
        ),
    ]
