# Generated by Django 4.0.5 on 2022-08-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0005_spareparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparts',
            name='status',
            field=models.CharField(choices=[('ava', 'Availabe'), ('nav', 'Not_Availabe'), ('chec', 'Received')], default='chec', max_length=4),
        ),
    ]
