# Generated by Django 4.0.5 on 2022-08-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0006_spareparts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='status',
            field=models.CharField(choices=[('ava', 'Availabe'), ('nav', 'Not_Availabe'), ('rec', 'Received')], default='rec', max_length=4),
        ),
    ]
