# Generated by Django 4.1 on 2022-09-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0007_alter_spareparts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='amcoolalphonce@gmail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='status',
            field=models.CharField(choices=[('ava', 'Availabe'), ('nav', 'Not Availabe'), ('rec', 'Received')], default='rec', max_length=4),
        ),
    ]
