# Generated by Django 4.1 on 2022-11-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneshop', '0008_order_email_alter_spareparts_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Phone Repair Order', 'verbose_name_plural': 'Phone Repair Orders'},
        ),
        migrations.AlterModelOptions(
            name='spareparts',
            options={'verbose_name': 'Sparepart', 'verbose_name_plural': 'Spareparts'},
        ),
        migrations.AddField(
            model_name='spareparts',
            name='email',
            field=models.EmailField(default='amcoolrepairshop@gmail.com', max_length=254, verbose_name='Email '),
        ),
    ]
